services:
  - type: web
    plan: free
    name: project
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: "python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
    - key: ChannelAccessToken
      sync: false
    - key: ChannelSecret
      sync: false
    - key: OPENAI_API_KEY
      sync: false
